apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespase: {{ .Values.namespase }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - name: http
    port: 9999
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.appName }}
    tier: frontend
  type: LoadBalancer